THITHUWEB/THITHUWEB/Controllers/TAISAN_61134311Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using THITHUWEB.Models;

namespace THITHUWEB.Controllers
{
    public class TAISAN_61134311Controller : Controller
    {
        private Thi61CNTT_61134311Entities db = new Thi61CNTT_61134311Entities();

        string LayMaTS()
        {
            var maMax = db.TAISANs.ToList().Select(n => n.MaTS).Max();
            int maTS = int.Parse(maMax.Substring(2)) + 1;
            string NV = String.Concat("000", maTS.ToString());
            return "TS" + NV.Substring(maTS.ToString().Length - 1);
        }
        public ActionResult TimKiem()
        {
            var taisan = db.TAISANs.Include(n => n.LOAITAISAN);
            return View(taisan.ToList());
        }
        [HttpPost]
        public ActionResult TimKiem(string maTS)
        {
            var taisan = db.TAISANs.Where(abc => abc.MaTS == maTS);
            return View(taisan.ToList());
        }
        [HttpGet]

        public ActionResult Search(string TenTS = "", string giaMin = "", string giaMax = "")
        {
            string min = giaMin, max = giaMax;
           
          
            ViewBag.TenTS = TenTS;
           
            if (giaMin == "")
            {
                ViewBag.giaMin = "";
                min = "0";
            }
            else
            {
                ViewBag.giaMin = giaMin;
                min = giaMin;
            }
            if (max == "")
            {
                max = Int32.MaxValue.ToString();
                ViewBag.giaMax = "";// Int32.MaxValue.ToString(); 
            }
            else
            {
                ViewBag.giaMax = giaMax;
                max = giaMax;
            }
           
            
            var taisan = db.TAISANs.SqlQuery("TaiSan_TimKiem'" + TenTS +"','" + min + "','" + max  + "'");
            if (taisan.Count() == 0)
                ViewBag.TB = "Không có thông tin tài sản cần tìm kiếm.";
            return View(taisan.ToList());
        }
        public ActionResult Index()
        {

            var taisan = db.TAISANs.Include(n => n.LOAITAISAN);
            return View(taisan.ToList());
        }

        // GET: NhanViens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TAISAN nhanVien = db.TAISANs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: NhanViens/Create
        public ActionResult Create()
        {

            ViewBag.MaTS = LayMaTS();
            ViewBag.MaLTS = new SelectList(db.LOAITAISANs, "MaLTS", "TenLTS");
            return View();
        }

        // POST: NhanViens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTS,TenTS,DVT,XuatSu,DonGia,AnhMH,MaLTS,GhiChu")] TAISAN taisan)
        {
            //System.Web.HttpPostedFileBase Avatar;
            var imgTS = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgTS.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            imgTS.SaveAs(path);

            if (ModelState.IsValid)
            {
                taisan.MaTS = LayMaTS();
                taisan.AnhMH = postedFileName;
                db.TAISANs.Add(taisan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaLTS = new SelectList(db.LOAITAISANs, "MaLTS", "TenLTS", taisan.MaTS);
            return View(taisan);
        }

        // GET: NhanViens/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TAISAN taisan = db.TAISANs.Find(id);
            if (taisan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLTS = new SelectList(db.LOAITAISANs, "MaLTS", "TenLTS", taisan.MaTS);
            return View(taisan);
        }

        // POST: NhanViens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTS,TenTS,DVT,XuatSu,DonGia,AnhMH,MaLTS,GhiChu")] TAISAN taisan)
        {
            var imgTS = Request.Files["Avatar"];
            try
            {
                //Lấy thông tin từ input type=file có tên Avatar
                string postedFileName = System.IO.Path.GetFileName(imgTS.FileName);
                //Lưu hình đại diện về Server
                var path = Server.MapPath("/Images/" + postedFileName);
                imgTS.SaveAs(path);
            }
            catch
            { }
            if (ModelState.IsValid)
            {
                db.Entry(taisan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLTS = new SelectList(db.LOAITAISANs, "MaLTS", "TenLTS", taisan.MaTS);

            return View(taisan);
        }

        // GET: NhanViens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TAISAN nhanVien = db.TAISANs.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            TAISAN nhanVien = db.TAISANs.Find(id);
            db.TAISANs.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

THITHUWEB/THITHUWEB/Views/TAISAN_61134311/Create.cshtml
@model THITHUWEB.Models.TAISAN

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .tieude {
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 2px;
        color: blue;
        text-align: center;
    }
</style>


@using (Html.BeginForm("Create", "TAISAN_61134311", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">
            <h3 class="tieude">Thêm mới tài sản</h3>
            <hr />
            <div class="row ">
                <div class="col-md-6">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.MaTS, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            <input type="text" value="@ViewBag.MaTS" disabled readonly class="form-control" />
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TenTS, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.TenTS, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenTS, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DVT, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.DVT, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DVT, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.XuatSu, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            <div class="checkbox">
                                Trong nước @Html.RadioButtonFor(model => model.XuatSu, "True", new { @checked = "checked" }) &nbsp;
                                Ngoại nhập @Html.RadioButtonFor(model => model.XuatSu, "False")
                                @Html.ValidationMessageFor(model => model.XuatSu, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <!--=========================-->
                <div class="col-md-6">


                    <div class="form-group">
                        @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AnhMH, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                            @Html.ValidationMessageFor(model => model.AnhMH, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.MaLTS, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownList("MaLTS", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MaLTS, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group ml-4">
                        <div class="col-md-offset-2 col-md-10 ml-auto">
                            <input type="submit" value="Create" class="btn btn-success" />

                            <button class="btn btn-warning " onclick="location.href='@Url.Action("Index", "TAISAN_61134311")';return false;">Trở về</button>
                        </div>
                    </div>
                </div>
                
            </div>

           


            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaTS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaTS" disabled readonly class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenTS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DVT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DVT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DVT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.XuatSu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Trong nước @Html.RadioButtonFor(model => model.XuatSu, "True", new { @checked = "checked" }) &nbsp;
                    Ngoại nhập @Html.RadioButtonFor(model => model.XuatSu, "False")
                    @Html.ValidationMessageFor(model => model.XuatSu, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhMH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.AnhMH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLTS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLTS", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLTS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>*@


        </div>
    </div>
}

THITHUWEB/THITHUWEB/Views/TAISAN_61134311/Delete.cshtml
@model THITHUWEB.Models.TAISAN

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string xs = "";
}

@*<h4 style="color:red;"> Bạn có chắc chắn xóa tài sản này?</h4>
    <table border="0" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
        <tr>
            <td>
                <table cellpadding="2" cellspacing="10">
                    <caption><b>THÔNG TIN CHI TIẾT</b></caption>
                    <tr>
                        <td rowspan="8"><img src="/Images/@Html.DisplayFor(model => model.AnhMH)" width="100" height="100" /></td>
                        <td>Mã tài sản:</td>
                        <td>@Html.DisplayFor(model => model.MaTS)</td>
                    </tr>
                    <tr>
                        <td>Tên tài sản:</td>
                        <td>@Html.DisplayFor(model => model.TenTS)</td>
                    </tr>

                    <tr>
                        <td>Xuất sứ:</td>
                        <td>
                            @{if (Model.XuatSu == true)
                                { xs = "Trong nước"; }
                                else
                                { xs = "Ngoại nhập"; }
                            }
                            @xs
                        </td>
                    </tr>
                    <tr>
                        <td>Đơn vị tính:</td>
                        <td>@Html.DisplayFor(model => model.DVT)</td>
                    </tr>
                    <tr>
                        <td>Đơn giá:</td>
                        <td>@Html.DisplayFor(model => model.DonGia)</td>
                    </tr>

                    <tr>
                        <td>Loại tài sản:</td>
                        <td>@Html.DisplayFor(model => model.LOAITAISAN.TenLTS)</td>
                    </tr>
                    <tr>
                        <td>Ghi chú:</td>
                        <td>@Html.DisplayFor(model => model.GhiChu)</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>*@



<!--========================-->
<style>
    .content {
        margin: 5px auto;
        width: 50%;
        border: 1px solid;
        justify-content: center;
        align-items: center;
        display: flex;
        font-size: 16px;
        font-weight: 600;
    }

    .EmpImg img {
        width: 200px;
        height: 200px;
        border-radius: 50%;
    }

    .tieude {
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 2px;
        color: blue;
        text-align: center;
    }

    .tieude {
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 2px;
        color: blue;
        text-align: center;
    }
</style>
<h3 class="tieude">Xoá tài sản</h3>
<div class="content">

    <div class="EmpImg">
        <img src="/Images/@Html.DisplayFor(model => model.AnhMH)" alt="Alternate Text" />
    </div>

    <div style="padding: 50px">
        <div style="display: flex; justify-content: center;">
            <div>
                <fieldset>
                    <legend>THÔNG TIN TÀI SẢN CẦN XOÁ </legend>

                    <table>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Mã tài sản: </td>
                            <td style="padding-bottom: 10px"><span>@Html.DisplayFor(model => model.MaTS)</span></td>
                        </tr>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Họ tên: </td>
                            <td style="padding-bottom: 10px"><span>@Html.DisplayFor(model => model.TenTS)</span></td>
                        </tr>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Xuất sứ: </td>
                            <td style="padding-bottom: 10px">
                                <span>
                                    @{if (Model.XuatSu == true)
                                        { xs = "Trong nước"; }
                                        else
                                        { xs = "Ngoại nhập"; }
                                    }
                                    @xs
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Đơn vị tính: </td>
                            <td style="padding-bottom: 10px"><span>@Html.DisplayFor(model => model.DVT)</span></td>
                        </tr>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Đơn giá: </td>
                            <td style="padding-bottom: 10px"><span>@Html.DisplayFor(model => model.DonGia)</span></td>
                        </tr>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Loại tài sản: </td>
                            <td style="padding-bottom: 10px"><span>@Html.DisplayFor(model => model.LOAITAISAN.TenLTS)</span></td>
                        </tr>
                        <tr>
                            <td style="padding-right: 10px; padding-bottom: 10px">Ghi chú: </td>
                            <td style="padding-bottom: 10px"><span>@Html.DisplayFor(model => model.GhiChu) </span></td>
                        </tr>

                    </table>
                </fieldset>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color" style="margin-left:50px;">
                <input type="submit" value="Xóa" class="btn btn-danger" /> |
                <button class="btn btn-warning" onclick="location.href='@Url.Action("Index", "TAISAN_61134311")';return false;">Trở về</button>
            </div>
        }

    </div>
</div>

THITHUWEB/THITHUWEB/Views/TAISAN_61134311/Details.cshtml
@model THITHUWEB.Models.TAISAN

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TAISAN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DVT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DVT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.XuatSu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.XuatSu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhMH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhMH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LOAITAISAN.TenLTS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOAITAISAN.TenLTS)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaTS }) |
    @Html.ActionLink("Back to List", "Index")
</p>

THITHUWEB/THITHUWEB/Views/TAISAN_61134311/Index.cshtml
@model IEnumerable<THITHUWEB.Models.TAISAN>

@{
    ViewBag.Title = "Index";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenTS", rowsPerPage: 5);
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!--================================================================================-->
<style type="text/css">
    .grid-footer {
        color: black;
        font: 17px Calibri;
        text-align: center;
        font-weight: 900;
    }

    .grid-footer a {
        background-color: #ffffff;
        color: black;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        padding: 1px 10px 2px 10px;
    }

    .grid-footer a:active, a:hover {
        background-color: #ffffff;
        color: blue;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: left;
    }
    .tieude {
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 2px;
        color: blue;
        text-align:center;
    }
</style>


<!--=======================================================-->
<h3 class="tieude">DANH SÁCH TÀI SẢN </h3>


@grid.GetHtml(
    tableStyle: "table table-bordered table-hover",
    footerStyle: "grid-footer",
    fillEmptyRows: true,
    mode: WebGridPagerModes.Numeric,
    alternatingRowStyle: "alternatingRowStyle",
    columns: new[]  
    {
        grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaTS","Mã tài sản"), //the model fields to display
        grid.Column("TenTS","Tên tài sản"  ),
        grid.Column("XuatSu","Xuất sứ",format: (@item) => @item.XuatSu==true?"Trong nước":"Ngoại nhập"),
        grid.Column("DonGia","Dơn giá",format:@<text> @item.DonGia.ToString("#,##0")</text>),
        grid.Column("DVT","Đơn vị tính"),
        grid.Column("AnhMH","Ảnh minh hoạ"),
        grid.Column("LOAITAISAN.TenLTS","Loại tài sản"),
        grid.Column("GhiChu","Ghi chú"),
        grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","TAISAN_61134311", new { id = item.MaTS },"TAISAN_61134311Controller")),

    }
)

THITHUWEB/THITHUWEB/Views/TAISAN_61134311/Search.cshtml
@model List<THITHUWEB.Models.TAISAN>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenTS", rowsPerPage: 2);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")

}
<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }

        .table1 input{
            margin:5px 10px;
        }
        .table1 td{
            font-size:14px;
            font-weight:600;
        }
        #tb {
            font-size: 14px;
            font-weight: 600;
            color: royalblue;
            margin: 10px 363px;
            
        }
        .tieude {
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 2px;
            color: blue;
            text-align: center;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("Search", "TAISAN_61134311", FormMethod.Get))
        {
            @Html.AntiForgeryToken()

            <h3 class="tieude">Tìm kiếm tài sản</h3>
            <table class="table1" align="center">

                <tr>
                    <td>Tên tài sản</td>
                    <td>
                        <input type="text" name="TenTS" value="@ViewBag.TenTS" class="my-2 mx-3" />
                    </td>

                </tr>


                <tr>
                    <td>Giá từ</td>
                    <td>
                        <input type="text" name="giaMin" value="@ViewBag.giaMin" />
                        Đến<input type="text" name="giaMax" value="@ViewBag.giaMax" />
                    </td>

                </tr>



                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" class="btn btn-success" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" class="btn btn-info" onclick="location.href='@Url.Action("Search", "TAISAN_61134311/Search")'" />

                    </td>
                </tr>
            </table>
        }
    </div>
    <div id="gridContent">
        <span id="tb"> @ViewBag.TB</span>
        @grid.GetHtml(
           tableStyle: "table table-bordered table-hover",
           footerStyle: "grid-footer",
           fillEmptyRows: true,
           mode: WebGridPagerModes.Numeric,
           alternatingRowStyle: "alternatingRowStyle",
             columns: new[]  // colums in grid
            {
        grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
       grid.Column("MaTS","Mã tài sản"), //the model fields to display
       grid.Column("TenTS","Tên tài sản"  ),

      grid.Column("XuatSu","Xuất sứ",format: (@item) => @item.XuatSu==true?"Trong nước":"Ngoại nhập"),

grid.Column("DonGia","Dơn giá",format:@<text> @item.DonGia.ToString("#,##0")</text>),
grid.Column("DVT","Đơn vị tính"),
grid.Column("AnhMH","Ảnh minh hoạ"),
grid.Column("LOAITAISAN.TenLTS","Loại tài sản"),
grid.Column("GhiChu","Ghi chú"),


}
)
    </div>
</body>
</html>