KT1705_61134311/Controllers/SinhvienKT1705_61134311Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KT1705_61134311.Models;

namespace KT1705_61134311.Controllers
{
    public class SinhvienKT1705_61134311Controller : Controller
    {
        private KT1705_61134311Entities db = new KT1705_61134311Entities();
        // GET: NhanViens_61134311
        public ActionResult Index()
        {
            var nhanViens = db.Sinhviens.Include(n => n.Lop);
            return View(nhanViens.ToList());
        }

        // GET: NhanViens_61134311/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sinhvien nhanVien = db.Sinhviens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: NhanViens_61134311/Create
        //public ActionResult Create()
        //{
        //    ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB");
        //    return View();
        //}

        // POST: NhanViens_61134311/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "MaNV,HoNV,TenNV,GioiTinh,NgaySinh,Luong,AnhNV,DiaChi,MaPB")] NhanVien nhanVien)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.NhanViens.Add(nhanVien);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
        //    return View(nhanVien);
        //}
        string LayMaSV()
        {
            var maMax = db.Sinhviens.ToList().Select(n => n.MaSV).Max();
            int maSV = int.Parse(maMax.Substring(2)) + 1;
            string SV = String.Concat("00", maSV.ToString());
            return "SV" + SV.Substring(maSV.ToString().Length - 1);
        }

        public ActionResult TimKiem(string maSV)
        {
            var sinhviens = db.Sinhviens.Where(abc => abc.MaSV == maSV);
            return View(sinhviens.ToList());
        }
        [HttpPost]
        public ActionResult TimKiem_61134311(string maSV)
        {

            //var nhanViens = db.NhanViens.SqlQuery("exec NhanVien_DS '"+maNV+"' ");
            /// var nhanViens = db.NhanViens.SqlQuery("SELECT * FROM NhanVien WHERE MaNV='" + maNV + "'");
            var sinhviens = db.Sinhviens.Where(abc => abc.MaSV == maSV);
            return View(sinhviens.ToList());
        }
        [HttpGet]

        public ActionResult TimKiemNC_61134311(string maSV = "", string hoTen = "")
        {
            
         
            var sinhviens = db.Sinhviens.SqlQuery("Sinhvien_Timkiem'" + maSV + "','" + hoTen + "'");
            if (sinhviens.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(sinhviens.ToList());
        }
        public ActionResult Create()
        {

            ViewBag.MaSV = LayMaSV();
            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop");
            return View();
        }

        // POST: NhanViens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSV,HoSV,TenSV,NgaySinh,GioiTinh,AnhNV,DiaChi,MaLop")] Sinhvien sinhvien)
        {
            //System.Web.HttpPostedFileBase Avatar;
            var imgSV = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgSV.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            imgSV.SaveAs(path);

            if (ModelState.IsValid)
            {
                sinhvien.MaSV = LayMaSV();
                sinhvien.AnhNV = postedFileName;
                db.Sinhviens.Add(sinhvien);
                try
                {
                    db.SaveChanges();
                }
                catch(Exception e)
                {

                }
               
                return RedirectToAction("Index");
            }

            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop", sinhvien.MaSV);
            return View(sinhvien);
        }

        // GET: NhanViens_61134311/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sinhvien sinhvien = db.Sinhviens.Find(id);
            if (sinhvien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLop = new SelectList(db.Lops, "MaLop", "TenLop", sinhvien.MaSV);
            return View(sinhvien);
        }

        // POST: NhanViens_61134311/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSV,HoSV,TenSV,NgaySinh,GioiTinh,AnhNV,DiaChi,MaLop")] Sinhvien sinhvien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sinhvien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaLop = new SelectList(db.Lops, "Malop", "TenLop",sinhvien.MaLop);
            return View(sinhvien);
        }

        // GET: NhanViens_61134311/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sinhvien sinhvien = db.Sinhviens.Find(id);
            if (sinhvien == null)
            {
                return HttpNotFound();
            }
            return View(sinhvien);
        }

        // POST: NhanViens_61134311/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Sinhvien sinhvien = db.Sinhviens.Find(id);
            db.Sinhviens.Remove(sinhvien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KT1705_61134311/Views/SinhvienKT1705_61134311/Create.cshtml
@model KT1705_61134311.Models.Sinhvien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>ĐĂNG KÝ THÔNG TIN NHÂN VIÊN</h3>


@using (Html.BeginForm("Create", "SinhvienKT1705_61134311", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sinhvien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaSV" disabled readonly class="form-control" />
                @Html.ValidationMessageFor(model => model.MaSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLop, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>

    @Html.ActionLink("Quay lại", "Index")
</div>

KT1705_61134311/Views/SinhvienKT1705_61134311/Delete.cshtml
@model KT1705_61134311.Models.Sinhvien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}

<h4 style="color:red;"> Bạn có chắc chắn xóa thông tin này?</h4>
<table border="0" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
    <tr>
        <td>
            <table cellpadding="2" cellspacing="10">
                <caption><b>THÔNG TIN CHI TIẾT</b></caption>
                <tr>
                    <td rowspan="8"><img src="/Images/@Html.DisplayFor(model => model.AnhNV)" width="100" height="100" /></td>
                    <td>Mã nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.MaSV)</td>
                </tr>
                <tr>
                    <td>Họ nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.HoSV)</td>
                </tr>
                <tr>
                    <td>Tên nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.TenSV)</td>
                </tr>
                <tr>
                    <td>Giới tính:</td>
                    <td>
                        @{if (Model.GioiTinh == true)
                            { gtinh = "Nam"; }
                            else
                            { gtinh = "Nữ"; }
                        }
                        @gtinh
                    </td>
                </tr>
                <tr>
                    <td>Ngày sinh:</td>
                    <td>@Html.DisplayFor(model => model.NgaySinh)</td>
                </tr>
               
                <tr>
                    <td>Địa chỉ:</td>
                    <td>@Html.DisplayFor(model => model.DiaChi)</td>
                </tr>
                <tr>
                    <td>Phòng ban:</td>
                    <td>@Html.DisplayFor(model => model.Lop.TenLop)</td>
                </tr>

            </table>
        </td>
    </tr>
</table>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color" style="margin-left:50px;">
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        @Html.ActionLink("Quay lại", "Index")
    </div>
}

KT1705_61134311/Views/SinhvienKT1705_61134311/Edit.cshtml
@model KT1705_61134311.Models.Sinhvien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(function () {
            var fileupload = $("#Avatar");
            var image = $("#FileUpload");
            image.click(function () {
                fileupload.click();
            });
            fileupload.change(function () {
                var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
                document.getElementById("AnhNV").value = fileName;
            });
        });
    </script>
}

<h3>CẬP NHẬT THÔNG TIN NHÂN VIÊN</h3>


@using (Html.BeginForm("Edit", "SinhvienKT1705_61134311", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSV)@Html.HiddenFor(model => model.Lop)

        <div class="form-group">
            @Html.LabelFor(model => model.HoSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">

                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
                <input type="file" name="Avatar" id="Avatar" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaLop, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLop", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLop, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập nhật" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

KT1705_61134311/Views/SinhvienKT1705_61134311/Index.cshtml
@model IEnumerable<KT1705_61134311.Models.Sinhvien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 2);
    string gtinh = "";
    int i = 0;


}

<style type="text/css">
    .grid-footer {
        color: #000;
        font: 17px Calibri;
        text-align: center;
        font-weight: bold;
    }

        .grid-footer a {
            background-color: #ffffff;
            color: blue;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            padding: 1px 10px 2px 10px;
        }

            .grid-footer a:active, a:hover {
                background-color: #ffffff;
                color: #FFAD33;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            }

    .alternatingRowStyle {
        background-color: aliceblue;
    }

    table .table1 {
        text-align: left;
        margin-left: 0px;
        margin-right: 0px;
        width: 800px;
    }

    .tr, .td {
        text-align: left;
    }
</style>

<h2>Thông tin sinh viên</h2>

@grid.GetHtml(
           tableStyle: "table table-bordered table-hover",
           footerStyle: "grid-footer",
           fillEmptyRows: true,
           mode: WebGridPagerModes.Numeric,
           alternatingRowStyle: "alternatingRowStyle",
             columns: new[]  // colums in grid
            {
        grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
       grid.Column("MaSV","Mã sinh viên"), //the model fields to display
       grid.Column("HoSV","Họ sinh viên"  ),
       grid.Column("TenSV","Tên sinh viên"),
        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),

grid.Column("DiaChi","Địa chỉ"),
grid.Column("Lop.TenLop","Lớp"),
//grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "SinhvienKT1705_61134311",new { id = item.MaSV },"SinhvienKT1705_61134311Controller")),
//grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","SinhvienKT1705_61134311", new { id = item.MaSV },"SinhvienKT1705_61134311Controller")),
//grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","SinhvienKT1705_61134311", new { id = item.MaSV },"SinhvienKT1705_61134311Controller")),
grid.Column("Chức năng", format: @<text>
            <a href="@Url.Action("Edit",
                        new { id = item.MaSV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Details",
                        new { id = item.MaSV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Delete",
                        new { id = item.MaSV})" class="edit-btn">
                <abbr title="Xóa dữ liệu">
                    <img src="/images/delete.png" width="20" height="20" />
                </abbr>
            </a>
</text>),

})

KT1705_61134311/Views/SinhvienKT1705_61134311/TimKiemNC_61134311.cshtml
@model List<KT1705_61134311.Models.Sinhvien>
@{
    ViewBag.Title = "TimKiemNC_61134311";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenSV", rowsPerPage: 2);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")

}
<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        <h3>TÌM KIẾM </h3>
        
        @using (Html.BeginForm("TimKiemNC_61134311", "SinhvienKT1705_61134311", FormMethod.Get))
        {
            @Html.AntiForgeryToken()


            <table class="table1" align="center">
                <tr>
                    <td>
                        <div> Mã nhân viên</div>
                    </td>
                    <td>
                        <input type="text" name="maSV" value="@ViewBag.maSV" />
                    </td>

                </tr>
                <tr>
                    <td>Họ tên</td>
                    <td>
                        <input type="text" name="hoTen" value="@ViewBag.hoTen" />
                    </td>

                </tr>

                <tr>
                    <td></td>
                    <td>
                        <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" />
                        <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiemNC_61134311", "SinhvienKT1705_61134311/TimKiemNC_61134311")'" />

                    </td>
                </tr>
            </table>
        }
    </div>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
           tableStyle: "table table-bordered table-hover",
           footerStyle: "grid-footer",
           fillEmptyRows: true,
           mode: WebGridPagerModes.Numeric,
           alternatingRowStyle: "alternatingRowStyle",
             columns: new[]  // colums in grid
            {
        grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
       grid.Column("MaSV","Mã sinh viên"), //the model fields to display
       grid.Column("HoSV","Họ sinh viên"  ),
       grid.Column("TenSV","Tên sinh viên"),
        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),

grid.Column("DiaChi","Địa chỉ"),
grid.Column("Lop.TenLop","Lớp"),
grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "SinhvienKT1705_61134311",new { id = item.MaSV },"SinhvienKT1705_61134311Controller")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","SinhvienKT1705_61134311", new { id = item.MaSV },"SinhvienKT1705_61134311Controller")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","SinhvienKT1705_61134311", new { id = item.MaSV },"SinhvienKT1705_61134311Controller")),
grid.Column("Chức năng", format: @<text>
            <a href="@Url.Action("Edit",
                        new { id = item.MaSV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Details",
                        new { id = item.MaSV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
            <a href="@Url.Action("Delete",
                        new { id = item.MaSV})" class="edit-btn">
                <abbr title="Xóa dữ liệu">
                    <img src="/images/delete.png" width="20" height="20" />
                </abbr>
            </a>
    </text>),


}
)
    </div>
</body>
</html>